"""Secure Aggregation mechanism for federated evaluation.

This mechanism implements pairwise-masking secure aggregation: each
hospital's score is additively masked with a net value derived from
random pairwise shares generated by a shared
:class:`SecureAggregationCoordinator`.  Because every pair contributes
``+m`` to the lexicographically smaller hospital and ``-m`` to the
larger one, the masks cancel **exactly** when all hospitals' masked
values are summed — allowing the server to recover the true aggregate
score without ever observing any individual hospital's true score.

Unlike the previous implementation, no original score or plaintext
mask is stored in record metadata.  The only metadata key written by
:meth:`apply` is the unclipped masked value
(``secure_agg_masked_value``), which is meaningless without knowing
the pairwise masks held by the coordinator.
"""

from __future__ import annotations

from dataclasses import replace
from typing import Sequence

from src.core.evaluation_record import EvaluationRecord
from src.federated.privacy.interfaces import PrivacyMechanism
from src.federated.privacy.secure_aggregation_coordinator import (
    SecureAggregationCoordinator,
)


class SecureAggregationMechanism(PrivacyMechanism):
    """Pairwise-masking secure aggregation for federated evaluation.

    Each hospital-side instance adds a per-round net mask (obtained
    from the shared :class:`SecureAggregationCoordinator`) to its
    local score before transmitting the record to the server.  The
    server-side :meth:`unmask` method recovers the true *per-hospital*
    scores by summing all masked values per prompt and distributing
    the result equally, since the sum of net masks across all
    hospitals is exactly zero.

    Attributes:
        _coordinator: Shared coordinator that generates pairwise masks.
        _hospital_id: Hospital identifier (required for hospital-side
            ``apply()``; ``None`` for server-only instances).
    """

    __slots__ = ("_coordinator", "_hospital_id")

    def __init__(
        self,
        coordinator: SecureAggregationCoordinator,
        hospital_id: str | None = None,
    ) -> None:
        """Initialize the Secure Aggregation mechanism.

        Args:
            coordinator: The **shared**
                :class:`SecureAggregationCoordinator` instance.  The
                **same** object must be passed to every hospital's
                mechanism instance AND to the server's mechanism
                instance, or masks will not cancel.
            hospital_id: Required (must not be ``None``) when this
                instance is used in the hospital-side :meth:`apply`
                role.  Leave ``None`` when this instance is **only**
                used server-side for :meth:`unmask` — ``hospital_id``
                is unused there.

        Raises:
            ValueError: If ``coordinator`` is ``None``.
        """
        if coordinator is None:
            raise ValueError(
                "SecureAggregationMechanism requires a non-None coordinator."
            )
        self._coordinator: SecureAggregationCoordinator = coordinator
        self._hospital_id: str | None = hospital_id

    # ------------------------------------------------------------------
    # Hospital-side: mask before transmission
    # ------------------------------------------------------------------

    def apply(
        self,
        records: Sequence[EvaluationRecord],
    ) -> Sequence[EvaluationRecord]:
        """Mask each record's score with the hospital's pairwise net mask.

        Called hospital-side, one record at a time (the existing call
        site passes a 1-tuple).  The :class:`Sequence` signature is
        retained for interface compatibility.

        For each record:

        1. Obtain the net mask from the coordinator for this
           ``(prompt_id, hospital_id)`` pair.
        2. Compute ``true_masked_value = record.score + net_mask``.
           This value is **not** clipped and is stored in metadata
           under ``secure_agg_masked_value`` for the server to read
           during :meth:`unmask`.
        3. Compute ``transit_score = clip(true_masked_value, 0, 1)``
           solely to satisfy :class:`EvaluationRecord`'s ``[0, 1]``
           structural invariant.  ``transit_score`` is **never** used
           for any real computation — :meth:`unmask` reads the
           unclipped ``secure_agg_masked_value`` from metadata, so
           clipping introduces zero error into the final result.
        4. Construct the masked record via :func:`dataclasses.replace`.
           No original score is stored in any form.

        Args:
            records: Evaluation records to mask.

        Returns:
            Masked copies of the input records.

        Raises:
            ValueError: If ``self._hospital_id`` is ``None`` (this
                instance was constructed for the server-only role and
                cannot apply masks).
        """
        if self._hospital_id is None:
            raise ValueError(
                "Cannot call apply() on a server-only "
                "SecureAggregationMechanism (hospital_id is None)."
            )

        if not records:
            return tuple()

        masked_records: list[EvaluationRecord] = []
        for record in records:
            net_mask = self._coordinator.get_net_mask(
                record.prompt_id, self._hospital_id
            )
            true_masked_value: float = record.score + net_mask

            # transit_score exists ONLY to satisfy EvaluationRecord's
            # [0, 1] invariant on .score.  It is NOT used for any real
            # computation — unmask() reads true_masked_value from
            # metadata, never .score — so clipping here introduces
            # zero error into the final result.
            transit_score = max(0.0, min(1.0, true_masked_value))

            masked_record = replace(
                record,
                score=transit_score,
                num_correct=int(round(transit_score * record.num_total)),
                metadata={
                    **record.metadata,
                    "secure_agg_masked_value": true_masked_value,
                    "secure_agg_masked": True,
                },
            )
            masked_records.append(masked_record)

        return tuple(masked_records)

    # ------------------------------------------------------------------
    # Server-side: recover true scores after collection
    # ------------------------------------------------------------------

    def unmask(
        self, records: Sequence[EvaluationRecord]
    ) -> Sequence[EvaluationRecord]:
        """Recover true per-hospital scores from masked records.

        Called server-side once per round, given **all** hospitals'
        masked records together (the existing call site in
        :class:`FederatedServer` already collects the full flattened
        list before calling this).

        The unmasking procedure relies on the exact cancellation
        property of pairwise masks: for any prompt, the sum of
        ``secure_agg_masked_value`` across all hospitals equals the
        sum of their true scores.

        For each unique ``prompt_id`` in the batch:

        1. Collect all ``secure_agg_masked_value`` entries for that
           prompt.
        2. Compute the aggregate (sum) of those values — because
           net masks cancel, this equals the sum of the true scores.
        3. Divide by the number of hospitals to obtain the mean true
           score.
        4. Reconstruct each record with the mean score (the server
           learns only the aggregate, never individual scores).
        5. Discard the round's cached pairwise masks via the
           coordinator to prevent reuse.

        Args:
            records: Masked :class:`EvaluationRecord` objects from
                **all** hospitals for this round.

        Returns:
            Unmasked records with true aggregate scores restored.

        Raises:
            ValueError: If any record is missing the
                ``secure_agg_masked_value`` metadata key.
        """
        if not records:
            return tuple()

        # Group records by prompt_id for per-prompt unmasking.
        from collections import defaultdict

        by_prompt: dict[str, list[tuple[int, EvaluationRecord]]] = defaultdict(list)
        for idx, record in enumerate(records):
            by_prompt[record.prompt_id].append((idx, record))

        unmasked: list[EvaluationRecord | None] = [None] * len(records)
        seen_prompts: set[str] = set()

        for prompt_id, entries in by_prompt.items():
            # Read the unclipped masked values from metadata.
            masked_values: list[float] = []
            for _, record in entries:
                masked_val = record.metadata.get("secure_agg_masked_value")
                if masked_val is None:
                    raise ValueError(
                        f"Record {record.prompt_id} from "
                        f"{record.hospital_id} missing "
                        f"'secure_agg_masked_value' in metadata."
                    )
                masked_values.append(float(masked_val))

            # Sum of masked values == sum of true scores (masks cancel).
            true_sum = sum(masked_values)
            n_hospitals = len(entries)
            mean_score = true_sum / n_hospitals

            # Clamp to [0, 1] to satisfy EvaluationRecord invariant
            # (floating-point rounding may push the value marginally
            # outside the valid range).
            mean_score = max(0.0, min(1.0, mean_score))

            for orig_idx, record in entries:
                unmasked[orig_idx] = replace(
                    record,
                    score=mean_score,
                    num_correct=int(round(mean_score * record.num_total)),
                    metadata={
                        **record.metadata,
                        "secure_agg_unmasked": True,
                    },
                )

            seen_prompts.add(prompt_id)

        # Discard pairwise masks for all finalized rounds.
        for prompt_id in seen_prompts:
            self._coordinator.discard_round(prompt_id)

        return tuple(r for r in unmasked if r is not None)

    # ------------------------------------------------------------------
    # Dunder helpers
    # ------------------------------------------------------------------

    def __str__(self) -> str:
        """Return a concise string representation."""
        return (
            f"SecureAggregationMechanism("
            f"hospital_id={self._hospital_id!r})"
        )

    def __repr__(self) -> str:
        """Return a detailed string representation."""
        return (
            f"SecureAggregationMechanism("
            f"coordinator={self._coordinator!r}, "
            f"hospital_id={self._hospital_id!r})"
        )