"""Parser for extracting candidate prompts generated by the mutation LLM."""

from __future__ import annotations

import re

__all__ = ["CandidateParser"]


class CandidateParser:
    """Parses the five candidate prompts returned by the mutation LLM.

    Expected format:

    === Candidate 1 ===
    <prompt>

    === Candidate 2 ===
    <prompt>

    ...

    === Candidate 5 ===
    <prompt>
    """

    _PATTERN = re.compile(
        r"=== Candidate (\d+) ===\s*(.*?)(?=(?:=== Candidate \d+ ===)|\Z)",
        flags=re.DOTALL,
    )

    def parse(self, text: str) -> list[str]:
        """Extracts the five candidate prompts.

        Args:
            text: Raw LLM output.

        Returns:
            A list containing exactly five candidate prompts.

        Raises:
            ValueError:
                If the output does not contain exactly five candidates
                numbered 1 through 5.
        """
        if not isinstance(text, str):
            raise TypeError(
                f"text must be str, got {type(text).__name__}."
            )

        matches = self._PATTERN.findall(text)

        if len(matches) != 5:
            raise ValueError(
                f"Expected 5 candidates, found {len(matches)}."
            )

        candidates: list[str] = []

        for expected_index, (number, prompt) in enumerate(matches, start=1):
            number = int(number)

            if number != expected_index:
                raise ValueError(
                    f"Expected Candidate {expected_index}, "
                    f"found Candidate {number}."
                )

            cleaned = prompt.strip()

            if not cleaned:
                raise ValueError(
                    f"Candidate {number} is empty."
                )

            candidates.append(cleaned)

        return candidates