"""Parser for extracting candidate prompts generated by the mutation LLM."""

from __future__ import annotations

import re

__all__ = ["CandidateParser"]


class CandidateParser:
    """Parses candidate prompts returned by the LLM.

    Expected format:

    === Candidate 1 ===
    <prompt>

    === Candidate 2 ===
    <prompt>

    ...

    === Candidate 5 ===
    <prompt>

    If the LLM returns fewer than 5 but at least 1 valid candidate,
    the parser returns whatever it found. If it finds 0 candidates
    in the expected format, it falls back to treating the entire
    raw output as a single candidate.
    """

    _PATTERN = re.compile(
        r"=== Candidate (\d+) ===\s*(.*?)(?=(?:=== Candidate \d+ ===)|\Z)",
        flags=re.DOTALL,
    )

    def parse(self, text: str) -> list[str]:
        """Extracts candidate prompts from LLM output.

        Args:
            text: Raw LLM output.

        Returns:
            A list of candidate prompt strings (1 to 5).

        Raises:
            TypeError: If text is not a string.
            ValueError: If no candidates can be extracted at all.
        """
        if not isinstance(text, str):
            raise TypeError(
                f"text must be str, got {type(text).__name__}."
            )

        matches = self._PATTERN.findall(text)

        if not matches:
            # Fallback: treat the entire output as a single candidate
            cleaned = text.strip()
            if not cleaned:
                raise ValueError(
                    "Expected candidates in '=== Candidate N ===' format, "
                    "but output was empty."
                )
            return [cleaned]

        candidates: list[str] = []

        for number_str, prompt in matches:
            cleaned = prompt.strip()
            if cleaned:
                candidates.append(cleaned)

        if not candidates:
            raise ValueError(
                "Found candidate headers but all candidate bodies were empty."
            )

        return candidates