MODEL_NAME = "Qwen/Qwen3-8B"

LOAD_IN_4BIT = True

MAX_NEW_TOKENS = 256

TEMPERATURE = 0.2

# GA hyperparameters
GA_POPULATION_SIZE = 10
GA_GENERATIONS     = 5
GA_MUTATION_RATE   = 0.3
GA_CROSSOVER_RATE  = 0.7
GA_TOURNAMENT_SIZE = 3
EVALUATION_SUBSET_SIZE = 100
RANDOM_SEED = 42